name: motradis
description: Moneytransfair project build on flutter.

dependencies:
  collection: '>=1.9.1 <2.0.0'
  intl: '>=0.14.0 <0.15.0'
  string_scanner: ^1.0.0

  flutter:
    sdk: flutter
  url_launcher: ^0.4.0
  shared_preferences: ^0.2.4

  # Also update dev/benchmarks/complex_layout/pubspec.yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: 0b6cdb29b24ecc60781c2828086d955dacdc0152

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  assets:
      - packages/flutter_gallery_assets/appbar_background.jpg
      - packages/flutter_gallery_assets/appbar/appbar_background_layer0.png
      - packages/flutter_gallery_assets/appbar/appbar_background_layer1.png
      - packages/flutter_gallery_assets/appbar/appbar_background_layer2.png
      - packages/flutter_gallery_assets/appbar/appbar_background_layer3.png
      - packages/flutter_gallery_assets/appbar/appbar_background_layer4.png
      - packages/flutter_gallery_assets/appbar/appbar_background_layer5.png
      - packages/flutter_gallery_assets/about_logo.png

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. Note: the `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700